services:
  web:
    build: .
    container_name: panagia_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: panagia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PANAGIAsenha
      MYSQL_DATABASE: panagia
      MYSQL_USER: adminPanagia
      MYSQL_PASSWORD: EG13062009TY456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
